/**
 * Blog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegraDeNegocioExceptionCauseStackTraceInner } from './regraDeNegocioExceptionCauseStackTraceInner';


export interface RegraDeNegocioExceptionCauseSuppressedInner { 
    stackTrace?: Array<RegraDeNegocioExceptionCauseStackTraceInner>;
    message?: string;
    localizedMessage?: string;
}

